# top level stuff you probably don't need to touch
highlighter: rouge
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: miguel.arroyo.me
baseurl: ""
title: Miguel A. Arroyo
author: Miguel A. Arroyo
description: A bit about myself
avatar: profile2.png
email: email@arroyo.me
github: mayanez # username
linkedin: mayanez
flickr: mayanez
twitter: miguelaarroyo12
gpgkeys: true
resumeurl: http://link.arroyo.me/miguelresume
google_analytics: UA-72068313-1

simhaurl: http://www.cs.columbia.edu/~simha/
castlurl: http://castl.cs.columbia.edu
candidacyslidesurl: https://drive.google.com/open?id=1rzTED_vJn01VIofbiSGkYJqQL_UI5R4cIJYwZjeUeUk
candidacysyllabusurl: https://drive.google.com/open?id=1jUkaPdekWI3F4IglRamCctUATu1fb9Fq 
yolopaperurl: https://drive.google.com/open?id=1Luut2_m9TmyqBJuD1xGEgDVVRWgqyKNF
yoloslidesurl: https://drive.google.com/open?id=1DWL73UbgIlcUZHjG_Ag8mMS8IFMjSZar_CVk7o0fsZU
yoloslidesdarsurl: https://drive.google.com/open?id=1rRBDyIuQVGbvypQc4NBzi08L40cruhycGCRU7f5nPlA
yolovideosurl: https://www.youtube.com/playlist?list=PL4UBpWp0d9Jq7_NP22SsiBwGRbMa6lPGH
yolobiburl: https://www.spiedigitallibrary.org/citation/download/citation-11009_.bib
yolodoi: 10.1117/12.2518909
asploswaciurl: https://drive.google.com/open?id=1R0FLs6rwKFB059FRbLvPEssaCpJVYcKfhCy2DQQvCAQ
ropslidesurl: https://drive.google.com/open?id=1rXGc_jSnR1Qcevr_ZyNbadboNxZ8J62JD5XXqUA5IJk
califormspaperurl: https://drive.google.com/open?id=1H-VBjNN63RJPhKnOYzHFKPeHiu-gFBqm 
califormsvideosurl: https://www.youtube.com/playlist?list=PL4UBpWp0d9Jq1TVTo6SbfMSAyLZR3y4wA
califormsposterurl: https://drive.google.com/open?id=1m_niaDoq1lujhqdJzyVZGkeFTbKa2A2o
califormsdoi: 0

# needed for travis-ci build
exclude: [vendor]
